# Generated by Django 4.2.7 on 2023-11-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="userlogIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("user_pswd", models.CharField(max_length=50)),
                ("create_date", models.DateTimeField(verbose_name="date created")),
            ],
        ),
    ]
