# Generated by Django 4.2.7 on 2023-12-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="scripts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scriptTxt", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="userlogin",
            name="employeeID",
            field=models.CharField(default=12345678, max_length=10),
            preserve_default=False,
        ),
    ]
