# Generated by Django 4.2.7 on 2023-12-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_scripts_userlogin_employeeid"),
    ]

    operations = [
        migrations.AddField(
            model_name="scripts",
            name="employeeID",
            field=models.CharField(default=10101010, max_length=10),
            preserve_default=False,
        ),
    ]
