
---
- name: Create security policies
  hosts: phoenix_firewall
  connection: local
  vars_files:
    - nic_vault.txt

  vars:
    ansible_python_interpreter: "/home/nic/nic_190/CSC190/venv/bin/python3"
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Add rule
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        rule_name: "nic_rule22"
        source_zone: ["Internet"]
        source_ip: ["10.0.0.129"]
        destination_zone: ["DMZ"]
        destination_ip: ["10.0.0.65"]
        application: ["ssh"]
        service: ["any"]
        action: "allow"
    