
---
- name: Create security policies
  hosts: phoenix_firewall
  connection: local
  vars_files:
    - nic_vault.txt

  vars:
    ansible_python_interpreter: "/home/nic/nic_190/CSC190/venv/bin/python3"
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Add rule
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        rule_name: "nic_rule5"
        source_zone: ["Internal"]
        source_ip: ["1.1.1.1"]
        destination_zone: ["Internet"]
        destination_ip: ["1.1.1.2"]
        application: ["ssh"]
        service: ["any"]
        action: "allow"
    