
---
- name: Create security policies
  hosts: phoenix_firewall
  connection: local
  vars_files:
    - nic_vault.txt

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Add rule
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        rule_name: "Test Rule"
        source_zone: ["Internal"]
        source_ip: ["10.0.0.1"]
        destination_zone: ["Internet"]
        destination_ip: ["10.0.0.129"]
        application: ["ssh"]
        service: ["tcp-22"]
        action: "allow"
  