---
- name: Delete security rule
  hosts: phoenix_firewall
  connection: local
  vars_files:
    - nic_vault.txt

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
      
  collections:  
    - paloaltonetworks.panos

  tasks:
    - name: Delete rule
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        rule_name: "up"
        source_ip: "1.1.1.1"
        port: 12345
        state: 'absent'
